---
version: '3.5'

networks:
  arc-integration:
    name: arc-integration
    driver: bridge
    ipam:
     config:
       - subnet: 172.19.0.0/24

services:
  sbt:
    container_name: sbt
    image: amazoncorretto:8
    networks:
      - arc-integration
    command: tail -F anything
    volumes:
      - ${PWD}:/app
      - /tmp/pgp:/pgp
    working_dir: /app

  zookeeper:
    image: confluentinc/cp-zookeeper:5.4.1
    networks:
      - arc-integration
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:5.4.1
    ports:
      - 9092:9092
    networks:
      - arc-integration
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_LISTENERS: CLIENT://kafka:29092,PLAINTEXT://kafka:29093
      KAFKA_ADVERTISED_LISTENERS: CLIENT://kafka:29092,PLAINTEXT://kafka:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CLIENT:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 10

  kafka-rest:
    image: confluentinc/cp-kafka-rest:5.4.1
    ports:
      - 8082:8082
    networks:
      - arc-integration
    depends_on:
      - zookeeper
      - kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_REST_BOOTSTRAP_SERVERS: kafka:29093
      KAFKA_REST_HOST_NAME: kafka-rest
      KAFKA_REST_LISTENERS: http://0.0.0.0:8082

  kafka-schema-registry:
    image: confluentinc/cp-schema-registry:5.4.1
    ports:
      - 8081:8081
    networks:
      - arc-integration
    depends_on:
      - zookeeper
      - kafka
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:32181